In [4]:
print("Working")

Working

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('/mnt/c/Users/aumpa/Downloads/archive/renewable_hydrogen_dataset.csv')

In [7]:
df.head(10)

,p_id2,start_year,season_days_injured,total_days_injured,season_minutes_played,season_games_played,season_matches_in_squad,total_minutes_played,total_games_played,dob,...,fifa_rating,position,age,bmi,work_rate_numeric,position_numeric,significant_injury_prev_season,cumulative_days_injured,season_days_injured_prev_season,target
0,1,2001,99,72,1242,32,39,13197,67,1970-01-01,...,79,Goalkeeper,33,29.825780,3,1,1,579,21,0
1,2,2012,46,40,1555,30,28,41893,254,1970-01-02,...,65,Defender,22,26.178197,1,1,0,396,39,0
2,3,2020,8,74,1726,19,26,11114,5,1970-01-03,...,63,Forward,34,19.251199,2,3,1,859,8,0
3,4,2000,20,178,1920,33,38,36125,445,1970-01-04,...,62,Defender,19,23.233480,1,1,0,425,57,0
4,5,2022,45,441,918,11,43,29573,33,1970-01-05,...,79,Defender,26,19.818891,3,4,0,994,26,0
5,6,2013,26,231,468,19,16,9222,119,1970-01-06,...,52,Goalkeeper,38,21.154421,1,2,0,385,49,0
6,7,2004,32,67,704,14,6,5120,231,1970-01-07,...,68,Midfielder,39,26.245584,2,4,0,605,13,1
7,8,2002,89,469,1520,1,30,33059,383,1970-01-08,...,70,Forward,35,22.698635,2,1,0,128,73,0
8,9,2014,55,361,803,22,13,3564,418,1970-01-09,...,56,Defender,24,21.842244,1,3,0,696,71,0
9,10,2020,69,152,1807,11,28,24080,230,1970-01-10,...,84,Midfielder,39,23.808390,3,3,1,721,42,0

In [8]:
df.isnull().sum()

p_id2                              0
start_year                         0
season_days_injured                0
total_days_injured                 0
season_minutes_played              0
season_games_played                0
season_matches_in_squad            0
total_minutes_played               0
total_games_played                 0
dob                                0
height_cm                          0
weight_kg                          0
nationality                        0
work_rate                          0
pace                               0
physic                             0
fifa_rating                        0
position                           0
age                                0
bmi                                0
work_rate_numeric                  0
position_numeric                   0
significant_injury_prev_season     0
cumulative_days_injured            0
season_days_injured_prev_season    0
target                             0
dtype: int64

In [10]:
df.describe()

,p_id2,start_year,season_days_injured,total_days_injured,season_minutes_played,season_games_played,season_matches_in_squad,total_minutes_played,total_games_played,height_cm,...,physic,fifa_rating,age,bmi,work_rate_numeric,position_numeric,significant_injury_prev_season,cumulative_days_injured,season_days_injured_prev_season,target
count,2535.00000,2535.000000,2535.000000,2535.000000,2535.000000,2535.000000,2535.000000,2535.000000,2535.000000,2535.000000,...,2535.000000,2535.000000,2535.000000,2535.000000,2535.000000,2535.000000,2535.000000,2535.000000,2535.000000,2535.000000
mean,1268.00000,2012.172781,49.181460,251.058383,1505.323077,18.423274,24.478107,24393.632742,253.691519,174.122288,...,63.334517,74.386588,28.555424,24.277299,2.007890,2.485207,0.500197,496.382643,48.484418,0.497830
std,731.93579,7.178586,28.958647,144.830406,869.419784,10.876664,14.373808,14369.939918,145.218857,14.360783,...,19.915769,14.080431,6.383865,3.353464,0.819514,1.120801,0.500099,285.370300,28.309731,0.500094
min,1.00000,2000.000000,0.000000,0.000000,1.000000,0.000000,0.000000,17.000000,0.000000,150.000000,...,30.000000,50.000000,18.000000,18.501140,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,634.50000,2006.000000,24.000000,129.000000,745.500000,9.000000,12.000000,11853.000000,129.000000,162.000000,...,46.000000,62.000000,23.000000,21.371139,1.000000,1.000000,0.000000,254.500000,24.000000,0.000000
50%,1268.00000,2012.000000,50.000000,250.000000,1528.000000,19.000000,25.000000,24079.000000,254.000000,174.000000,...,63.000000,75.000000,29.000000,24.316627,2.000000,2.000000,1.000000,500.000000,47.000000,0.000000
75%,1901.50000,2018.000000,74.000000,377.000000,2251.500000,27.000000,36.000000,36486.500000,383.000000,186.000000,...,80.000000,86.000000,34.000000,27.196426,3.000000,3.000000,1.000000,732.000000,73.000000,1.000000
max,2535.00000,2024.000000,99.000000,499.000000,2999.000000,37.000000,49.000000,49999.000000,499.000000,199.000000,...,98.000000,98.000000,39.000000,29.995620,3.000000,4.000000,1.000000,999.000000,99.000000,1.000000

In [11]:
df2 = pd.read_csv('/mnt/c/Users/aumpa/Downloads/archive/renewable_hydrogen_dataset_2535.csv')
df.head(10)

,p_id2,start_year,season_days_injured,total_days_injured,season_minutes_played,season_games_played,season_matches_in_squad,total_minutes_played,total_games_played,dob,...,fifa_rating,position,age,bmi,work_rate_numeric,position_numeric,significant_injury_prev_season,cumulative_days_injured,season_days_injured_prev_season,target
0,1,2001,99,72,1242,32,39,13197,67,1970-01-01,...,79,Goalkeeper,33,29.825780,3,1,1,579,21,0
1,2,2012,46,40,1555,30,28,41893,254,1970-01-02,...,65,Defender,22,26.178197,1,1,0,396,39,0
2,3,2020,8,74,1726,19,26,11114,5,1970-01-03,...,63,Forward,34,19.251199,2,3,1,859,8,0
3,4,2000,20,178,1920,33,38,36125,445,1970-01-04,...,62,Defender,19,23.233480,1,1,0,425,57,0
4,5,2022,45,441,918,11,43,29573,33,1970-01-05,...,79,Defender,26,19.818891,3,4,0,994,26,0
5,6,2013,26,231,468,19,16,9222,119,1970-01-06,...,52,Goalkeeper,38,21.154421,1,2,0,385,49,0
6,7,2004,32,67,704,14,6,5120,231,1970-01-07,...,68,Midfielder,39,26.245584,2,4,0,605,13,1
7,8,2002,89,469,1520,1,30,33059,383,1970-01-08,...,70,Forward,35,22.698635,2,1,0,128,73,0
8,9,2014,55,361,803,22,13,3564,418,1970-01-09,...,56,Defender,24,21.842244,1,3,0,696,71,0
9,10,2020,69,152,1807,11,28,24080,230,1970-01-10,...,84,Midfielder,39,23.808390,3,3,1,721,42,0

In [13]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2535 entries, 0 to 2534
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   p_id2                            2535 non-null   int64
 1   start_year                       2535 non-null   int64
 2   season_days_injured              2535 non-null   int64
 3   total_days_injured               2535 non-null   int64
 4   season_minutes_played            2535 non-null   int64
 5   season_games_played              2535 non-null   int64
 6   season_matches_in_squad          2535 non-null   int64
 7   total_minutes_played             2535 non-null   int64
 8   total_games_played               2535 non-null   int64
 9   dob                              2535 non-null   object
 10  height_cm                        2535 non-null   int64
 11  weight_kg                        2535 non-null   int64
 12  nationality                      2535 non-null   object
 13  work_rate                        2535 non-null   object
 14  pace                             2535 non-null   int64
 15  physic                           2535 non-null   int64
 16  fifa_rating                      2535 non-null   int64
 17  position                         2535 non-null   object
 18  age                              2535 non-null   int64
 19  bmi                              2535 non-null   float64
 20  work_rate_numeric                2535 non-null   int64
 21  position_numeric                 2535 non-null   int64
 22  significant_injury_prev_season   2535 non-null   int64
 23  cumulative_days_injured          2535 non-null   int64
 24  season_days_injured_prev_season  2535 non-null   int64
 25  target                           2535 non-null   int64
dtypes: float64(1), int64(21), object(4)
memory usage: 515.1+ KB
None

In [ ]:
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2535 entries, 0 to 2534
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   p_id2                            2535 non-null   int64
 1   start_year                       2535 non-null   int64
 2   season_days_injured              2535 non-null   int64
 3   total_days_injured               2535 non-null   int64
 4   season_minutes_played            2535 non-null   int64
 5   season_games_played              2535 non-null   int64
 6   season_matches_in_squad          2535 non-null   int64
 7   total_minutes_played             2535 non-null   int64
 8   total_games_played               2535 non-null   int64
 9   dob                              2535 non-null   object
 10  height_cm                        2535 non-null   int64
 11  weight_kg                        2535 non-null   int64
 12  nationality                      2535 non-null   object
 13  work_rate                        2535 non-null   object
 14  pace                             2535 non-null   int64
 15  physic                           2535 non-null   int64
 16  fifa_rating                      2535 non-null   int64
 17  position                         2535 non-null   object
 18  age                              2535 non-null   int64
 19  bmi                              2535 non-null   float64
 20  work_rate_numeric                2535 non-null   int64
 21  position_numeric                 2535 non-null   int64
 22  significant_injury_prev_season   2535 non-null   int64
 23  cumulative_days_injured          2535 non-null   int64
 24  season_days_injured_prev_season  2535 non-null   int64
 25  target                           2535 non-null   int64
dtypes: float64(1), int64(21), object(4)
memory usage: 515.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2535 entries, 0 to 2534
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   City                         2535 non-null   object
 1   Latitude                     2535 non-null   float64
 2   Longitude                    2535 non-null   float64
 3   Solar_Irradiance_kWh/mÂ²/day  2535 non-null   float64
 4   Temperature_C                2535 non-null   float64
 5   Wind_Speed_m/s               2535 non-null   float64
 6   PV_Power_kW                  2535 non-null   int64
 7   Wind_Power_kW                2535 non-null   int64
 8   Electrolyzer_Efficiency_%    2535 non-null   float64
 9   Hydrogen_Production_kg/day   2535 non-null   int64
 10  Desalination_Power_kW        2535 non-null   float64
 11  System_Efficiency_%          2535 non-null   float64
 12  Feasibility_Score            2535 non-null   float64
dtypes: float64(9), int64(3), object(1)
memory usage: 257.6+ KB
None